//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBAccess.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Items
    {
        public Items()
        {
            this.StockData = new HashSet<StockData>();
        }
    
        public int Id { get; set; }
        public string Ticker { get; set; }
        public string InstrumentCode { get; set; }
        public string MarketCode { get; set; }
        public System.DateTime DateFrom { get; set; }
        public System.DateTime DateTo { get; set; }
        public int InstrumentId { get; set; }
        public byte Period { get; set; }
    
        public virtual Instruments Instrument { get; set; }
        public virtual ICollection<StockData> StockData { get; set; }
    }
}
